# what language the build will be configured for
language: python

# note that all of the versions listed will be tried
python:
  - "3.6"

# what branches should be evaluated
branches:
  only:
    - master
    - structure_extract

# list of commands to run to setup the environment
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install --upgrade setuptools
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements.txt
  - pip install pylint

# a list of commands to run before the main script
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
#  - "flake8 dopedefects"

script:
#  - pylint --ignore="tests" dopedefects/
  - py.test -s --pyargs dopedefects --cov-report term-missing --cov=dopedefects --cov-config .coveragerc

# generate a coverage report to send to back to user
after_success:
  - coveralls
